---
- hosts: node2
  remote_user: root
  
  vars:
    hosts:
    - name: www.robertzwj.com
      port: 8082
    - name: jenkins.robertzwj.com
      port: 8083
  tasks:
  - name: create nginx confi of template
    template: src=nginx.conf2.j2 dest=/etc/nginx/conf.d/nginx.conf
    notify: restart nginx
  - name: start nginx
    service: name=nginx state=started

  handlers:
  - name: restart nginx
    shell: nginx -s reload
